---
- hosts: localhost
  connection: local
  tasks:
      - name: Clean tomcat_hosts
        ansible.builtin.known_hosts:
            state: absent
            name: "{{ hostvars[item].ansible_host if hostvars[item].ansible_host is defined else item }}"
        with_items: "{{ groups['tomcat_hosts'] }}"
        ignore_errors: true


- hosts: tomcat_hosts
  gather_facts: true
  become: true
  become_method: sudo
  vars:
    tomcat_ver: 8.5.40
    ui_manager_user: manager                    # User who can access the UI manager section only
    ui_manager_pass: Str0ngManagerP@ssw3rd      # UI manager user password
    ui_admin_username: admin                    # User who can access bpth manager and admin UI sections
    ui_admin_pass: Str0ngAdminP@ssw3rd          # UI admin password
  roles:
    - role: tomcat

# - hosts: localhost
#   connection: local
#   vars:
#     - root_dir: ''
#   tasks:
#       - name: Build war file
#         shell:
#           cmd: mvn package
#           chdir: "{{ root_dir }}"